### ISSUE TITLE
[BUG] btop4win-LHM-x64.zip is flagged by Windows Defender as containing a trojan virus

### ISSUE THREAD

**Issue by CharleyFrench** [aristocratos/btop4win#57]
Windows Defender identifies a trojan in the containing folder for the "btop" program.
Trojan:Win32/Vigorf.A
File affected: C:\Users\[USERNAME]\Downloads\btop4win-LHM-x64\btop4win\btop4win.sys

<img width="1281" height="1001" alt="Image" src="https://github.com/user-attachments/assets/0fc2ff1f-a8f2-4b17-854a-cd7d83b674f9" />

**To Reproduce**

Download "btop4win-LHM-x64.zip"

Extract files to any folder

**Expected behavior**

Extracting the files should cause no issues
 - btop4win version: 1.0.4
 - Architecture: 64bit,
 - Windows Version: 10

**Comment by aristocratos** [comment]
Should be fixed in [latest release](https://github.com/aristocratos/btop4win/releases/tag/v1.0.5)

**Comment by s3603591** [comment]
This is still a recurring issue.

**Comment by aristocratos** [comment]
Yeah noticed.
Looks like the issue could be fixed in Libre Hardware Monitors beta version of 0.9.5, but when testing other stuff broke...

For now the only solutions are either to add an exception in Windows Defender or run the non LHM version of btop4win and wait for LHM 0.9.5 to be released.

**Comment by ddc** [comment]
This still an issue with v1.0.5

<img width="920" height="560" alt="Image" src="https://github.com/user-attachments/assets/2d6c75e0-c885-450f-88e2-a4bf024f2e4b" />

**Comment by aristocratos** [comment]
@ddc 
Where you expecting something else considering the comment above?

> For now the only solutions are either to add an exception in Windows Defender or run the non LHM version of btop4win and wait for LHM 0.9.5 to be released.

**Comment by ddc** [comment]
@aristocratos 
Yes, that comment explicit says to:

> wait for LHM 0.9.5 to be released

The version I've showed was v1.0.5
That's why I've said:
>This **_still_** an issue with **_v1.0.5_**

**Comment by aristocratos** [comment]
@ddc 
LHM = [Libre Hardware Monitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor), which is the library used for GPU monitoring in btop4win.

Current version of LHM is 0.9.4

**Comment by wtfolivr** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

Updated to 0.9.5. Error below is shown when newer LHM dll replaces older version.

```
2026/01/04 (07:46:52) | ===> btop++ v.1.0.5
2026/01/04 (07:46:52) | ERROR: Invalid RGB decimal value: "ba1a84"

2026/01/05 (22:53:36) | ===> btop++ v.1.0.5
2026/01/05 (22:53:36) | ERROR: Error during Libre Hardware Monitor parsing: invalid stoi argument

2026/01/05 (22:57:59) | ===> btop++ v.1.0.5
2026/01/05 (22:57:59) | ERROR: Error during Libre Hardware Monitor parsing: invalid stoi argument

2026/01/13 (08:27:49) | ===> btop++ v.1.0.5
2026/01/13 (08:27:49) | ERROR: Error during Libre Hardware Monitor parsing: invalid stoi argument
```

**Comment by magicxor** [comment]
I got the same message today 

<img width="2301" height="1650" alt="Image" src="https://github.com/user-attachments/assets/13d1079f-1f29-4384-a473-898cd6ed58db" />

**Comment by matt-edmondson** [comment]
> https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
> 
> Updated to 0.9.5. Error below is shown when newer LHM dll replaces older version.

It's not a good idea to replace a dll with a new version if the author of the application hasn't updated the application to be compatible with the new library. You're effectively breaking the contract between what the application expects to library to do, and how to interface with it.

Yes, sometimes it can work, but that's only accidental, not by design.

**Comment by tolga-balci** [comment]
I confirm that **_v1.0.5_** still has this issue.

> [@aristocratos](https://github.com/aristocratos) Yes, that comment explicit says to:
> 
> > wait for LHM 0.9.5 to be released
> 
> The version I've showed was v1.0.5 That's why I've said:
> 
> > This **_still_** an issue with **_v1.0.5_**
